### ISSUE TITLE
HessianMatrix.calculateMatrix() returns all zeros

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2-algorithm#77]
Starting with 0.11.0, the `HessianMatrix.calculateMatrix()` call returns all zeros, in cases where 0.10.0 and earlier returned non-zero results. See [this gist](https://gist.github.com/etarena/7b598da1dc7e06d46fd99623d35cf5b1) for a minimal example.

CC: @maarzt @tpietzsch

**Comment by tpietzsch** [comment]
The only thing that changed between these releases is the new Gauss implementation by @maarzt.
Something must be wrong with that. Maybe it's computing intermediate results in the wrong type?
@maarzt can you investigate please?

Quick workaround would be to go back to previous Gauss implementation. (But because nothing else changed, we can also just go back to 0.10.0 downstream...)

**Comment by maarzt** [comment]
The problem was caused, by the ExecuterService used (newCachedThreadPool). When you ask it, for the number of threads it uses, it returns Integer.MAX_VALUE. The new gauss implementation does so, and fails when it wants to distributes task to Integer.MAX_VALUE threads. Number overflow etc...

@tpietzsch the linked PR fixes the problem: https://github.com/imglib/imglib2-algorithm/pull/78

**Comment by ctrueden** [comment]
Thanks guys!
